In [1]:
#!pip install spacy

In [2]:
#!python -m spacy download en

In [24]:
nlp = spacy.load('en_core_web_sm') 

In [25]:
## import libraries
import numpy as np
from numpy import linalg as LA
from scipy import spatial
import spacy
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import cosine_distances

### Cosine Similarity
We are going to take three words 'King','Man','Woman' and calculate king-man+woman and check the cosine similarities and cosine distance between all of them.
Also we need to convert these words to vectors before checking the similarities and distances.

In [26]:
## create the vector for king
king=nlp('king').vector.reshape(1,-1)
king.shape

(1, 96)

In [27]:
## create the vector for king
man=nlp('man').vector.reshape(1,-1)
man.shape

(1, 96)

In [28]:
## create the vector for king
woman=nlp('woman').vector.reshape(1,-1)
woman.shape

(1, 96)

In [29]:
## let's check the final vector
new_vec=king-man+woman.reshape(1,-1)
new_vec.shape

(1, 96)

In [30]:
## create a function to calculate cosine_similarity between two words
cos_similarity = lambda word1,word2:cosine_similarity(word1,word2)

In [31]:
## Check cosine_similarity between king and man
cos_similarity(king,man)

array([[0.7189876]], dtype=float32)

In [32]:
## Directly also we can check similarity between two words
print(cosine_similarity(king,man))

[[0.7189876]]


In [34]:
## cosine_similarity between king and woman
print(cosine_similarity(king,woman))
cos_similarity(king,woman)

[[0.714959]]


array([[0.714959]], dtype=float32)

In [41]:
## cosine_similarity between woman and man
print(cosine_similarity(woman,man))
cos_similarity(woman,man)

[[0.8626202]]


array([[0.8626202]], dtype=float32)

In [42]:
## cosine_similarity between woman and new_vec
print(cosine_similarity(new_vec,woman))
cos_similarity(new_vec,woman)

[[0.7483405]]


array([[0.7483405]], dtype=float32)

In [43]:
#cosine_similarity between man and new_vec
print(cosine_similarity(new_vec,man))
cos_similarity(new_vec,man)

[[0.49752417]]


array([[0.49752417]], dtype=float32)

In [44]:
##cosine_similarity between king and new_vec
print(cosine_similarity(new_vec,king))
cos_similarity(new_vec,king)

[[0.8743261]]


array([[0.8743261]], dtype=float32)

In [45]:
## check similarity between two vectors
v1=np.array([[1,1,0,1,1]])
v2=np.array([[0,1,0,1,1]])
print(cosine_similarity(v1,v2))

[[0.8660254]]


### Cosine Distance
* Manually: Cosine Distance = 1- cosine similarity
* This can also be calculated directly using cosine_distances library

In [46]:
## calculate cosine distance manually
cos_distance=1-cosine_similarity(v1,v2)
cos_distance

array([[0.1339746]])

In [47]:
## calculate cosine distance directly using the cosine_distances library
from sklearn.metrics.pairwise import cosine_distances
print(cosine_distances(v1,v2))

[[0.1339746]]


In [48]:
## cosine distance between man and woman
print(cosine_distances(man,woman))

[[0.13737983]]


In [49]:
## cosine distance between man and king
print(cosine_distances(man,king))

[[0.28101242]]


In [50]:
## cosine distance between woman and king
print(cosine_distances(woman,king))

[[0.28504097]]


### Dot Product and Cross Product

In [51]:
# Taking two 2D array
# For 2-D arrays it is the matrix product
a = [[2, 1], [0, 3]]
b = [[1, 1], [3, 2]]
 
# Calculating dot product using dot()
print(np.dot(a, b))

[[5 4]
 [9 6]]


In [52]:
# Calculating cross product using dot()
print(np.cross(a,b))

[ 1 -9]


### Eigen values and Eigen vectors

In [53]:
import numpy as np
from numpy import linalg as LA
input = np.array([[2,-1],[4,3]])
w, v = LA.eig(input)
print(w)
print(v)

[2.5+1.93649167j 2.5-1.93649167j]
[[-0.1118034 +0.4330127j -0.1118034 -0.4330127j]
 [ 0.89442719+0.j         0.89442719-0.j       ]]
